FC = gfortran

flags_gfortran = -std=f2003 -Wall -Wno-maybe-uninitialized -pedantic
flags_ifort = -O0 -warn all

FFLAGS = ${flags_$(FC)}

critical: LDLIBS = -llapack -lblas

needless = .DS_Store ebmb.pyc manual/ebmb.aux manual/.ebmb.lb manual/ebmb.log manual/ebmb.out manual/ebmb.synctex.gz ~temporary.dat

# generated by makemake90 mod=modules:

modules_gfortran = -Jmodules
modules_ifort = -module modules

override FFLAGS += ${modules_$(FC)}

needless += eliashberg/eigenvalue.o eliashberg/eigenvalue_cdos.o eliashberg/self_energy.o eliashberg/self_energy_cdos.o eliashberg/spectral_function.o io/load.o io/store.o io/tell.o programs/critical.o programs/ebmb.o programs/tc.o real_axis/dos.o real_axis/pade.o real_axis/real_axis.o universal/eigenvalues.o universal/formatting.o universal/global.o universal/tools.o modules/*.mod

programs = critical ebmb tc

.PHONY: all clean cleaner

all: $(programs)

clean:
	rm -f $(needless)

cleaner: clean
	rm -f $(programs)

$(programs):
	$(FC) $(FFLAGS) -o $@ $^ $(LDLIBS)

%.o: %.f90
	$(FC) $(FFLAGS) -c $< -o $@

critical: eliashberg/eigenvalue.o eliashberg/eigenvalue_cdos.o eliashberg/self_energy.o eliashberg/spectral_function.o io/load.o programs/critical.o universal/eigenvalues.o universal/global.o universal/tools.o
ebmb: eliashberg/self_energy.o eliashberg/self_energy_cdos.o eliashberg/spectral_function.o io/load.o io/store.o io/tell.o programs/ebmb.o real_axis/dos.o real_axis/pade.o real_axis/real_axis.o universal/formatting.o universal/global.o universal/tools.o
tc: eliashberg/self_energy.o eliashberg/self_energy_cdos.o eliashberg/spectral_function.o io/load.o programs/tc.o universal/formatting.o universal/global.o universal/tools.o

eliashberg/eigenvalue.o: eliashberg/self_energy.o universal/eigenvalues.o universal/global.o
eliashberg/eigenvalue_cdos.o: eliashberg/spectral_function.o universal/eigenvalues.o universal/global.o
eliashberg/self_energy.o: eliashberg/spectral_function.o universal/global.o universal/tools.o
eliashberg/self_energy_cdos.o: eliashberg/spectral_function.o universal/global.o
eliashberg/spectral_function.o: universal/global.o universal/tools.o
io/load.o: eliashberg/spectral_function.o universal/global.o universal/tools.o
io/store.o: universal/global.o
io/tell.o: universal/formatting.o universal/global.o
programs/critical.o: eliashberg/eigenvalue.o eliashberg/eigenvalue_cdos.o io/load.o universal/global.o
programs/ebmb.o: eliashberg/self_energy.o eliashberg/self_energy_cdos.o io/load.o io/store.o io/tell.o real_axis/dos.o real_axis/real_axis.o universal/global.o
programs/tc.o: eliashberg/self_energy.o eliashberg/self_energy_cdos.o io/load.o universal/formatting.o universal/global.o
real_axis/dos.o: eliashberg/self_energy.o universal/global.o
real_axis/pade.o: universal/global.o
real_axis/real_axis.o: real_axis/pade.o universal/global.o universal/tools.o
universal/eigenvalues.o: universal/global.o universal/tools.o
universal/formatting.o: universal/global.o
universal/tools.o: universal/global.o
