FC = gfortran

flags_gfortran = -std=f2003 -pedantic -Wall -Wno-maybe-uninitialized
flags_ifort = -O0 -stand f03 -warn all
flags_ifx = ${flags_ifort}

libs_gfortran = -llapack -lblas
libs_ifort = -lmkl_core -lmkl_intel_lp64 -lmkl_sequential
libs_ifx = ${libs_ifort}

FFLAGS = ${flags_$(FC)}

bin/critical: LDLIBS = ${libs_$(FC)}

needless = .DS_Store ebmb.pyc manual/ebmb.aux manual/.ebmb.lb manual/ebmb.log manual/ebmb.out manual/ebmb.synctex.gz ~temporary.dat

# generated by makemake90 bin=bin mod=build obj=build src=src:

modules_gfortran = -Jbuild
modules_ifort = -module build
modules_ifx = ${modules_ifort}

override FFLAGS += ${modules_$(FC)}

needless += build/critical.o build/dos.o build/ebmb.o build/eigenvalues.o build/eliashberg_eigenvalue.o build/eliashberg_eigenvalue_cdos.o build/eliashberg_self_energy.o build/eliashberg_self_energy_cdos.o build/eliashberg_self_energy_real_axis.o build/eliashberg_spectral_function.o build/formatting.o build/global.o build/io_load.o build/io_store.o build/io_tell.o build/pade.o build/real_axis.o build/tc.o build/tools.o build/*.mod

programs = bin/critical bin/ebmb bin/tc

.PHONY: all clean cleaner

all: $(programs)

clean:
	rm -f $(needless)

cleaner: clean
	rm -f $(programs)

$(programs):
	$(FC) $(FFLAGS) -o $@ $^ $(LDLIBS)

build/%.o: src/%.f90
	$(FC) $(FFLAGS) -c $< -o $@

bin/critical: build/critical.o build/eigenvalues.o build/eliashberg_eigenvalue.o build/eliashberg_eigenvalue_cdos.o build/eliashberg_self_energy.o build/eliashberg_spectral_function.o build/global.o build/io_load.o build/tools.o
bin/ebmb: build/dos.o build/ebmb.o build/eliashberg_self_energy.o build/eliashberg_self_energy_cdos.o build/eliashberg_self_energy_real_axis.o build/eliashberg_spectral_function.o build/formatting.o build/global.o build/io_load.o build/io_store.o build/io_tell.o build/pade.o build/real_axis.o build/tools.o
bin/tc: build/eliashberg_self_energy.o build/eliashberg_self_energy_cdos.o build/eliashberg_spectral_function.o build/formatting.o build/global.o build/io_load.o build/tc.o build/tools.o

build/critical.o: build/eliashberg_eigenvalue.o build/eliashberg_eigenvalue_cdos.o build/global.o build/io_load.o
build/dos.o: build/eliashberg_self_energy.o build/global.o build/pade.o build/tools.o
build/ebmb.o: build/dos.o build/eliashberg_self_energy.o build/eliashberg_self_energy_cdos.o build/eliashberg_self_energy_real_axis.o build/global.o build/io_load.o build/io_store.o build/io_tell.o build/real_axis.o
build/eigenvalues.o: build/global.o build/tools.o
build/eliashberg_eigenvalue.o: build/eigenvalues.o build/eliashberg_self_energy.o build/global.o
build/eliashberg_eigenvalue_cdos.o: build/eigenvalues.o build/eliashberg_spectral_function.o build/global.o
build/eliashberg_self_energy.o: build/eliashberg_spectral_function.o build/global.o build/tools.o
build/eliashberg_self_energy_cdos.o: build/eliashberg_spectral_function.o build/global.o
build/eliashberg_self_energy_real_axis.o: build/eliashberg_self_energy.o build/eliashberg_spectral_function.o build/global.o build/tools.o
build/eliashberg_spectral_function.o: build/global.o build/tools.o
build/formatting.o: build/global.o
build/io_load.o: build/eliashberg_spectral_function.o build/global.o build/tools.o
build/io_store.o: build/global.o
build/io_tell.o: build/formatting.o build/global.o
build/pade.o: build/global.o
build/real_axis.o: build/global.o build/pade.o build/tools.o
build/tc.o: build/eliashberg_self_energy.o build/eliashberg_self_energy_cdos.o build/formatting.o build/global.o build/io_load.o
build/tools.o: build/global.o
