# generated by makemake.py

compiler = gfortran
optional = -std=f2003 -Wall -pedantic
external = 
needless = *.dat *.out *.pyc ~temporary.* .DS_Store
programs = dos eb

.PHONY: all clean cleaner

all: $(programs)

clean:
	@rm -f $(needless) arguments.mod arguments.o dos.o eliashberg.mod eliashberg.o filenames.mod filenames.o global.mod global.o integration.mod integration.o intervals.mod intervals.o io.mod io.o main.o pade.mod pade.o realaxis.mod realaxis.o tc.mod tc.o

cleaner: clean
	@rm -f $(programs)

$(programs):
	@echo link $@
	@$(compiler) -o $@ $^ $(external)

%.o: %.f90
	@echo compile $*
	@$(compiler) $(optional) -c $< -o $@

dos: arguments.o dos.o global.o intervals.o
eb: arguments.o eliashberg.o filenames.o global.o integration.o intervals.o io.o main.o pade.o realaxis.o tc.o

dos.o: arguments.o global.o intervals.o
eliashberg.o: global.o
integration.o: global.o
intervals.o: global.o
io.o: filenames.o global.o integration.o
main.o: arguments.o eliashberg.o global.o io.o realaxis.o tc.o
pade.o: global.o
realaxis.o: global.o intervals.o pade.o
tc.o: eliashberg.o global.o
